#include <stdio.h>
#include <stdint.h>

/* =====================================================
   APPLICATION LAYER
   -----------------------------------------------------
   - Contains business logic
   - Must NOT know anything about CAN, PDU, or BSW
   ===================================================== */

// RTE API prototype generated by using Autosar tool like Davinci EBtresos etc
void Rte_Write_DoorCmd(uint8_t value);

//Application Code
void DoorControl_Runnable(void)
{
    // Logical signal value 0 = Unlock, 1 = Lock
    uint8_t DoorCmd = 1;

    printf("Application: DoorCmd = %d (Lock)\n", DoorCmd);

    //Application writes the signal via RTE It does NOT call COM or CAN directly,value is stored in rte buffer
    Rte_Write_DoorCmd(DoorCmd);
}

/* =====================================================
   RTE LAYER (Runtime Environment)
   -----------------------------------------------------
   - Bridges Application and BSW
   - Ensures isolation and safety
   ===================================================== */

//COM API prototype
void Com_SendSignal(uint8_t value);

//RTE write function
void Rte_Write_DoorCmd(uint8_t value)
{
   
    printf("RTE: Received DoorCmd from Application\n");

    // RTE forwards the signal to COM Application does NOT know this happens
    Com_SendSignal(value);
}

/* =====================================================
   COM LAYER
   -----------------------------------------------------
   - Stores signals
   - Packs signals into IPDUs
   - Decides WHEN to transmit
   ===================================================== */

// COM internal signal buffer
uint8_t ComSignalBuffer;

//COM IPDU buffer (simplified)
uint8_t IPduBuffer;

// PDU Router API prototype
void PduR_ComTransmit(void);

void Com_SendSignal(uint8_t value)
{
    // Store signal in COM internal buffer
    printf("COM: Storing DoorCmd in COM signal buffer\n");
    ComSignalBuffer = value;

    // Pack signal into IPDU
     //  (In real AUTOSAR this is bit-level packing)
    printf("COM: Packing DoorCmd into IPDU buffer\n");
    IPduBuffer = ComSignalBuffer;

    // Immediate transmission (In deferred mode this happens later in Com_MainFunctionTx())
    PduR_ComTransmit();
}

/* =====================================================
   PDU ROUTER (PduR)
   -----------------------------------------------------
   - Routes PDUs between BSW modules
   - Technology independent
   ===================================================== */

void CanIf_Transmit(void);

void PduR_ComTransmit(void)
{
    printf("PduR: Routing IPDU to CAN Interface\n");
    CanIf_Transmit();
}

/* =====================================================
   CAN INTERFACE (CanIf)
   -----------------------------------------------------
   - Hardware abstraction
   - Independent of CAN controller
   ===================================================== */

void Can_Write(void);

void CanIf_Transmit(void)
{
    printf("CanIf: Passing CAN frame to CAN Driver\n");
    Can_Write();
}

/* =====================================================
   CAN DRIVER (MCAL)
   -----------------------------------------------------
   - Talks directly to CAN hardware
   ===================================================== */

void Can_Write(void)
{
    printf("CAN Driver: CAN frame transmitted on CAN bus\n");
}

/* =====================================================
   MAIN FUNCTION
   -----------------------------------------------------
   - Simulates ECU startup
   ===================================================== */

int main(void)
{
    //Code start from here
    DoorControl_Runnable();
    return 0;
}
